name: event_management
description: "Event Management System - Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # HTTP and API
  http: ^1.2.1
  dio: ^5.4.2
  
  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Navigation
  go_router: ^16.0.0
  
  # UI Components
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # Forms and Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  
  # Location
  geolocator: ^14.0.2
  google_maps_flutter: ^2.5.3
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  
  # Image Handling
  image_picker: ^1.0.7
  
  # Animations
  lottie: ^3.1.0
  
  # Utils
  equatable: ^2.0.5
  uuid: ^4.3.3
  
  # Notifications
  flutter_local_notifications: ^19.3.0
  
  # File handling
  path_provider: ^2.1.2
  
  # Payment
  flutter_stripe: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
